# PDS PRACTICAL 4

**NAME:VARAD VIJAY AMBEKAR**

**DIV: SY-A**

**ROLL NO.- A-02**

**Aim - Numerical Computation with NumPy: Perform different computations using
 NumPy library.**

**1 . Explain the role of NumPy in the Python scientific computing ecosystem.**

Role of NumPy in the Python Scientific Computing Ecosystem

NumPy (Numerical Python) is the core library for numerical and scientific computing in Python.

Key roles:
Provides a powerful N-dimensional array object (ndarray)
Acts as a foundation for other libraries like Pandas, Matplotlib, and Scikit-learn
Supports fast mathematical operations on large datasets
Helps in working with:
Linear algebra
Statistics
Random number generation

**2.Why is NumPy Faster than Pure Python?**

NumPy is faster than regular Python because:

 a. Uses compiled code (C language)
NumPy operations are written in C, not pure Python
This makes execution much faster

b. Vectorization
Works on entire arrays at once instead of loops
Example:

for i in range(len(a)):

    c[i] = a[i] + b[i]

c = a + b

c. Less memory usage
Arrays store data more efficiently than Python lists

d. Better CPU usage
Uses optimized algorithms and memory handling



**3  . What types of mathematical operations can be performed using NumPy?**

Types of Mathematical Operations in NumPy

NumPy supports a wide range of operations:

a. Basic arithmetic

Addition, subtraction, multiplication, division

a + b, a - b, a * b, a / b


b. Statistical operations

Mean, median, standard deviation
np.mean(a), np.std(a)


c. Linear algebra

Matrix multiplication, determinant, inverse

np.dot(a, b)

 d. Trigonometric functions

sin, cos, tan

np.sin(a), np.cos(a)

e. Exponential and logarithmic

np.exp(a), np.log(a)

f. Random number generation

np.random.rand()

**4.Explain indexing and slicing in NumPy arrays.**
Indexing and Slicing in NumPy Arrays

1.Indexing:

Access specific elements using position:

a[0]    
a[2]     


2D Indexing

a[1, 2]   

3.Slicing

Extract a range of elements:

a[1:4]    

a[::2]

2D slicing

a[0:2, 1:3]

Indexing = get one value

Slicing = get multiple values

**5.How does NumPy integrate with libraries like:**


**a.	Pandas**

**b.	Matplotlib**

**c.	Scikit-learn**

**a. Pandas**

Pandas uses NumPy internally
DataFrames are built on NumPy arrays

import pandas as pd

df = pd.DataFrame(np.array([[1,2],[3,4]]))


**b. Matplotlib**

Used for plotting graphs

NumPy generates numerical data for plots

import matplotlib.pyplot as plt

x = np.arange(0, 10)

y = x**2

plt.plot(x, y)


**c. Scikit-learn**

Machine learning library

Uses NumPy arrays for input data

from sklearn.linear_model import LinearRegression

model.fit(X, y)


In [ ]:
import numpy as np

In [ ]:
arr1 = np.array([5, 10, 15, 20])
arr2 = np.arange(2, 20, 3)
arr3 = np.linspace(1, 10, 5)
arr4 = np.zeros((2, 3))
arr5 = np.ones((3, 3))
arr6 = np.eye(3)

print("Array:", arr1)
print("Arange:", arr2)
print("Linspace:", arr3)
print("Zeros:\n", arr4)
print("Ones:\n", arr5)
print("Identity Matrix:\n", arr6)

Array: [ 5 10 15 20]
Arange: [ 2  5  8 11 14 17]
Linspace: [ 1.    3.25  5.5   7.75 10.  ]
Zeros:
 [[0. 0. 0.]
 [0. 0. 0.]]
Ones:
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
Identity Matrix:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
import numpy as np

a = np.array([2, 4, 6, 8])
b = np.array([1, 3, 5, 7])

print("Addition:", a + b)
print("Subtraction:", a - b)
print("Multiplication:", a * b)
print("Division:", a / b)
print("Power:", a ** 2)

Addition: [ 3  7 11 15]
Subtraction: [1 1 1 1]
Multiplication: [ 2 12 30 56]
Division: [2.         1.33333333 1.2        1.14285714]
Power: [ 4 16 36 64]


In [ ]:
import numpy as np

x = np.array([[1, 2], [3, 4]])
y = np.array([[5, 6], [7, 8]])

print("Matrix Multiplication:\n", np.dot(x, y))
print("Transpose of x:\n", x.T)

Matrix Multiplication:
 [[19 22]
 [43 50]]
Transpose of x:
 [[1 3]
 [2 4]]


In [ ]:
import numpy as np

a = np.array([10, 20, 30, 40])
b = np.array([15, 20, 25, 40])

print("Greater than:", a > b)
print("Equal:", a == b)
print("Logical AND:", np.logical_and(a > 15, b > 20))
print("Logical OR:", np.logical_or(a < 20, b > 30))

Greater than: [False False  True False]
Equal: [False  True False  True]
Logical AND: [False False  True  True]
Logical OR: [ True False False  True]


In [ ]:
import numpy as np

a = np.array([1, 2, 3, 4])

print("Square Root:", np.sqrt(a))
print("Sine Values:", np.sin(a))
print("Log Values:", np.log(a))
print("Exponential:", np.exp(a))

Square Root: [1.         1.41421356 1.73205081 2.        ]
Sine Values: [ 0.84147098  0.90929743  0.14112001 -0.7568025 ]
Log Values: [0.         0.69314718 1.09861229 1.38629436]
Exponential: [ 2.71828183  7.3890561  20.08553692 54.59815003]


In [ ]:
import numpy as np

arr = np.array([[4, 8, 12], [16, 20, 24]])

print("Sum:", arr.sum())
print("Row-wise Sum:", arr.sum(axis=1))
print("Column-wise Sum:", arr.sum(axis=0))
print("Maximum:", arr.max())
print("Minimum:", arr.min())
print("Mean:", arr.mean())

Sum: 84
Row-wise Sum: [24 60]
Column-wise Sum: [20 28 36]
Maximum: 24
Minimum: 4
Mean: 14.0


In [ ]:
import numpy as np

data = np.array([12, 18, 25, 30, 35, 40])

print("Median:", np.median(data))
print("Standard Deviation:", np.std(data))
print("Variance:", np.var(data))
print("Argmax:", np.argmax(data))
print("Argmin:", np.argmin(data))

Median: 27.5
Standard Deviation: 9.585869229698936
Variance: 91.88888888888887
Argmax: 5
Argmin: 0


In [ ]:
import numpy as np

a = np.array([9, 3, 6, 1, 9, 3, 7])

print("Sorted Array:", np.sort(a))
print("Unique Elements:", np.unique(a))

Sorted Array: [1 3 3 6 7 9 9]
Unique Elements: [1 3 6 7 9]


**Conclusion:**

Thus, the practical on NumPy array methods and operations was successfully completed. Different methods of creating arrays such as
array(), arange(), linspace(), zeros(), ones(), and identity matrices were implemented and understood clearly. Various operations
including arithmetic operations, matrix operations, comparison and logical methods, mathematical functions, reduction functions, and
statistical methods were also performed on different arrays.
This practical helped in gaining a clear understanding of how NumPy makes numerical computations faster and more efficient
compared to normal Python lists. It also improved the understanding of multidimensional arrays, element-wise operations, matrix
manipulation, and data analysis functions such as mean, median, variance, and standard deviation.
Overall, the practical enhanced knowledge of NumPy as an important library for scientific computing, data analysis, and machine
learning applications in Python